//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTDownloaderWpf.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YTDownloaderWpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a _Add video.
        /// </summary>
        public static string ADD_VIDEO {
            get {
                return ResourceManager.GetString("ADD_VIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a YAYDownloader - Yet Another Youtube Downloader.
        /// </summary>
        public static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MP3 correctly saved to &quot;{0}&quot;.
        /// </summary>
        public static string COMMAND_MSG_END_MP3 {
            get {
                return ResourceManager.GetString("COMMAND_MSG_END_MP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} currently downloaded.
        /// </summary>
        public static string COMMAND_MSG_PROGRESS_DOWNLOAD {
            get {
                return ResourceManager.GetString("COMMAND_MSG_PROGRESS_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MP3 extraction: done {0}, out of {1}.
        /// </summary>
        public static string COMMAND_MSG_PROGRESS_MP3 {
            get {
                return ResourceManager.GetString("COMMAND_MSG_PROGRESS_MP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Now extracting MP3 from &quot;{0}&quot;.
        /// </summary>
        public static string COMMAND_MSG_START_MP3 {
            get {
                return ResourceManager.GetString("COMMAND_MSG_START_MP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Correctly downloaded {0} to &quot;{1}&quot;.
        /// </summary>
        public static string COMMAND_MSG_SUCCESS_DOWNLOAD {
            get {
                return ResourceManager.GetString("COMMAND_MSG_SUCCESS_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fetching video URI.
        /// </summary>
        public static string COMMAND_MSG_URI_SEARCH {
            get {
                return ResourceManager.GetString("COMMAND_MSG_URI_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a URL does not represent any reachable resource, aborting task creation.
        /// </summary>
        public static string DIALOG_INVALID_URL {
            get {
                return ResourceManager.GetString("DIALOG_INVALID_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Download.
        /// </summary>
        public static string DOWNLOAD {
            get {
                return ResourceManager.GetString("DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert URL and Name here.
        /// </summary>
        public static string INSERT_URL_NAME_HERE {
            get {
                return ResourceManager.GetString("INSERT_URL_NAME_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Message.
        /// </summary>
        public static string METADATA_TASK_MESSAGE {
            get {
                return ResourceManager.GetString("METADATA_TASK_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        public static string METADATA_TASK_NAME {
            get {
                return ResourceManager.GetString("METADATA_TASK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Status.
        /// </summary>
        public static string METADATA_TASK_STATUS {
            get {
                return ResourceManager.GetString("METADATA_TASK_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Formats.
        /// </summary>
        public static string METADATA_TASK_VIDEOS {
            get {
                return ResourceManager.GetString("METADATA_TASK_VIDEOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap YAYDownloader {
            get {
                object obj = ResourceManager.GetObject("YAYDownloader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
